### ISSUE TITLE
PDF Preview stops updating

### ISSUE THREAD

**Issue by KalKolberg** [sebbrudzinski/Open-LaTeX-Studio#133] opened 2016-08-08 00:19 UTC
Not sure what is causing this issue yet, but PDF Preview frequently stops updating.  I suspect it loses track of the viewer at some point and therefore rather than pointing to the current window it's pointing to a window that is no longer in use.   Further investigation required to get repeatable demonstration of the problem.

**Comment by KalKolberg** [comment] 2016-08-08 00:22
Note this might not be a problem with the Preview page at all.  Generating PDF code while in this state gives the same incorrect view.  Perhaps it's a problem with the temp PDF file.

**Comment by KalKolberg** [comment] 2016-08-08 00:32
Looks like the problem comes from any error in the tex file.  If anything is broken PDF Preview will not show an update until the problem is fixed.  Need to look into pdfbox and see if we can get any feedback when there is a failure.

**Comment by sebbrudzinski** [comment] 2016-08-23 16:49
We currently treat it as a feature, not a bug. The pdfbox cannot provide us with any information, because it does not even get to render the image if there's a problem with the tex file. What currently happens is that when LaTeX distribution is unable to generate a PDF from the provided source, we just leave the previous one on display. Changing this behaviour (to what?) is a part of this ticket: #4 

Having said that, I'll close this as a duplicate.

**Closed by sebbrudzinski** 2016-08-23 16:49 UTC
