### ISSUE TITLE
PDF preview window does not match the text in the Text Editor window

### ISSUE THREAD

**Issue by LloydBG** [sebbrudzinski/Open-LaTeX-Studio#31] opened 2015-07-02 13:34 UTC
Description:
The pdf preview windows does not match the text in the Text Editor window.

Steps to Recreate:
1. Open LaTex Studio
2. Open a document to edit or update
3. Type "<" and ">" without the quotation marks

Expected Result:
The pdf preview window should display both "<" and ">" correctly

Actual Result:
The pdf preview windows displayed and inverted "!" and "?"

Screenshot:
Windows 7
![image](https://cloud.githubusercontent.com/assets/13062974/8478027/3ae8c798-2101-11e5-8271-d963c842fa46.png)

Linux - Ubuntu 14.04.2
![image](https://cloud.githubusercontent.com/assets/13062974/8478161/19bbdafa-2102-11e5-8eb9-76d70157aaa7.png)

**Comment by LordFarin** [comment] 2016-04-26 20:10
This is not a bug. This is because the default font encoding pdflatex uses isn't identical to what we expect for < and >. See https://tex.stackexchange.com/questions/2369.

Putting
\usepackage[T1]{fontenc}
at the top resolves the problem.

**Comment by sebbrudzinski** [comment] 2016-04-26 20:30
I'll be looking into upgrading to PDFBox 2.0 as a part of this ticket: #33 Unfortunately, 2.0 brings some breaking changes for us. I'll verify both tickets once we have upgraded.

**Comment by sebbrudzinski** [comment] 2016-08-30 19:48
Should be fixed by https://github.com/sebbrudzinski/Open-LaTeX-Studio/pull/140

**Closed by sebbrudzinski** 2016-08-30 19:48 UTC
Labels: bug
